### Class exercise: table
![](../../images/numpy_slice_ex.png)
- on the above image find the 5 different slicings using only the array slicing notation

In [24]:
# the following line is jupyter notebook specific 
%matplotlib inline
import numpy as np

a = np.arange(10, 30).reshape(4, 5)

yellow = a[0,0];
lightBlue = a[:, 1]
blue = a[0:3:2, 4]
red = a[0, 1:4]
green = a[0:3, 2]


print(yellow)
print(lightBlue)
print(blue)
print(red)
print(green)

10
[11 16 21 26]
[14 24]
[11 12 13]
[12 17 22]


In [28]:
cube = np.arange(0, 27).reshape((3, 3, 3)) # = (z, y, x)

print(cube[1, 1, :])
print(cube[:, 1, 0])
print(cube[0, 2, :])

[12 13 14]
[ 3 12 21]
[6 7 8]
